name: CI Test for clingoLP

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: clingoLP
          environment-file: environment.yml
          auto-activate-base: false
      - name: Install clingoLP
        run: |
          python setup.py install
      - name: Test
        run: |
          clingoLP example_instance.lp example_encoding.lp --show-lp-solution
