name: CI Test for clingoLP

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: clingoLP
      - name: Install clingoLP
        run: |
          conda init bash
          exec bash
          conda activate clingoLP
          python setup.py install --user
      - name: Test
        run: |
          ~/.local/bin/clingoLP example_instance.lp example_encoding.lp --show-lp-solution
